### ISSUE TITLE
SDK: Add support for cover router and calling into CoverBroker

### ISSUE THREAD

**Issue by roxdanila** [NexusMutual/sdk#110]
Details here: https://www.notion.so/nxmcommunity/EtherFi-Integration-d305f7679569456f9fa54c807d8d6a80

**Comment by rackstar** [comment]
Tasks:

- [x] Add [getQuoteAndBuyCoverInputs](https://www.notion.so/nxmcommunity/EtherFi-Integration-d305f7679569456f9fa54c807d8d6a80?pvs=4#cbd9d331a5034f559f6bf2d9ec046d3b)
  - [x] returns DisplayInfo and buyCoverInput
  - [x] input validation
  - [ ] CoverRouter response validation
  - [ ] retrieve available capacity on "Not enough capacity" error
