### ISSUE TITLE
Fix `v0.3.x` of sdk crashing the frontend app

### ISSUE THREAD

**Issue by Gideonnn** [NexusMutual/sdk#123]
Ever since the sdk has been bumped from `0.2.x` to `0.3.x` the sdk crashes the consuming projects. I suspect this has something to do with the esm/commonjs module setup.

The error:
```
Dynamic require of "fs" is not supported
```

**Comment by rackstar** [comment]
@Gideonnn as discussed you have the fix for this so I'm assigning it to you
