### ISSUE TITLE
[listing] Product Listings | Week of 26 June 2024

### ISSUE THREAD

**Issue by BraveNewDeFi** [NexusMutual/sdk#161]
# Product Listing Request

New Product Listing Spreadsheet: https://docs.google.com/spreadsheets/d/184TFMw3onXav_1YaFkdAcn295cJ1Qtk9sIQDO83rG_M/edit?usp=sharing

## Onchain data

Product Name: Dialectic Moonphase
Annex link (optional): https://drive.google.com/file/d/1LSFtbMBmMr1-kLPm3kX6nqY0m2l8mdZb/view?usp=sharing
Schedule link (optional): 

## SDK data

Category (i.e. Yield Optimizer. only for public products): 
Private or Public?: Private
Logo (attach link to Google Drive SVG file): https://github.com/NexusMutual/frontend-react/blob/dev/public/logos/nexus-mutual.svg

## Onchain data

Product Name: Dialectic Chronograph
Annex link (optional): https://drive.google.com/file/d/1nMzK4_dlVYz76qCXZxJeKqhSBOXxqz-R/view?usp=sharing
Schedule link (optional): 

## SDK data

Category (i.e. Yield Optimizer. only for public products): 
Private or Public?: Private
Logo (attach link to Google Drive SVG file): https://github.com/NexusMutual/frontend-react/blob/dev/public/logos/nexus-mutual.svg

## Onchain data

Product Name: Spectra
Annex link (optional): 
Schedule link (optional):

## SDK data

Category (i.e. Yield Optimizer. only for public products): Yield Optimizer 
Private or Public?: Public
Logo (attach link to Google Drive SVG file): https://drive.google.com/file/d/1D8nSWEqulaNgWr01znrvqKdOTej6ZEMH/view?usp=sharing

## Onchain data

Product Name: Origin OUSD
Annex link (optional): https://drive.google.com/file/d/1YzsKnm0KCxMBiX4VsT-fMTOtSIvNk89a/view?usp=sharing
Schedule link (optional):

## SDK data

Category (i.e. Yield Optimizer. only for public products): Yield Optimizer 
Private or Public?: Public
Logo (attach link to Google Drive SVG file): https://github.com/NexusMutual/frontend-react/blob/dev/public/logos/originusd.svg

## Onchain data

Product Name: Mellow (P2P Market) + Symbiotic
Annex link (optional): https://drive.google.com/file/d/1j8rZDPp49cOrNs4dnQmt0sFvFuVvAVib/view?usp=sharing
Schedule link (optional):

## SDK data

Category (i.e. Yield Optimizer. only for public products): Liquid Restaking 
Private or Public?: Public
Logo (attach link to Google Drive SVG file):
https://drive.google.com/file/d/1qllevh1q5H0N7Z3fYIMMBTvROieQsWmw/view?usp=sharing
https://github.com/NexusMutual/frontend-react/blob/dev/public/logos/symbiotic.png

## Onchain data

Product Name: Mellow (Steakhouse Market) + Symbiotic
Annex link (optional): https://drive.google.com/file/d/13RJprmpcgsIsgM9TPWtZzflFFwOhztT_/view?usp=sharing
Schedule link (optional): 

## SDK data

Category (i.e. Yield Optimizer. only for public products): Liquid Restaking 
Private or Public?: Public
Logo (attach link to Google Drive SVG file):
https://drive.google.com/file/d/1qllevh1q5H0N7Z3fYIMMBTvROieQsWmw/view?usp=sharing
https://github.com/NexusMutual/frontend-react/blob/dev/public/logos/symbiotic.png

## Onchain data

Product Name: Mellow (RE7 Labs Market) + Symbiotic
Annex link (optional): https://drive.google.com/file/d/1omWefRF12aY1WjEJNPVLkl5PA60FzGoP/view?usp=sharing
Schedule link (optional):

## SDK data

Category (i.e. Yield Optimizer. only for public products): Liquid Restaking 
Private or Public?: Public
Logo (attach link to Google Drive SVG file):
https://drive.google.com/file/d/1qllevh1q5H0N7Z3fYIMMBTvROieQsWmw/view?usp=sharing
https://github.com/NexusMutual/frontend-react/blob/dev/public/logos/symbiotic.png

## Onchain data

Product Name: Mellow (MEV Capital Market) + Symbiotic
Annex link (optional): https://drive.google.com/file/d/1mQ6n2oBtB7RNK87FwOWaGVG_1E6KIwWw/view?usp=sharing
Schedule link (optional): 

## SDK data

Category (i.e. Yield Optimizer. only for public products): Liquid Restaking 
Private or Public?: Public
Logo (attach link to Google Drive SVG file):
https://drive.google.com/file/d/1qllevh1q5H0N7Z3fYIMMBTvROieQsWmw/view?usp=sharing
https://github.com/NexusMutual/frontend-react/blob/dev/public/logos/symbiotic.png

## Onchain data

Product Name: rstETH Symbiotic + Mellow + Pendle
Annex link (optional): https://drive.google.com/file/d/1M8oYdsGEmoXPropx0OeWwj9cBJjmNBlY/view?usp=sharing
Schedule link (optional):

## SDK data

Category (i.e. Yield Optimizer. only for public products): Yield Optimizer
Private or Public?: Public
Logo (attach link to Google Drive SVG file):
https://github.com/NexusMutual/frontend-react/blob/dev/public/logos/symbiotic.png
https://drive.google.com/file/d/1qllevh1q5H0N7Z3fYIMMBTvROieQsWmw/view?usp=sharing
https://github.com/NexusMutual/frontend-react/blob/dev/public/logos/pendle.svg

## Onchain data

Product Name: amphrETH Symbiotic + Mellow + Pendle
Annex link (optional): https://drive.google.com/file/d/1JXuoVpsXbd4AVDT-RX-U3Jti049kBKzq/view?usp=sharing
Schedule link (optional): 

## SDK data

Category (i.e. Yield Optimizer. only for public products): Yield Optimizer 
Private or Public?: Public
Logo (attach link to Google Drive SVG file):
https://github.com/NexusMutual/frontend-react/blob/dev/public/logos/symbiotic.png
https://drive.google.com/file/d/1qllevh1q5H0N7Z3fYIMMBTvROieQsWmw/view?usp=sharing
https://github.com/NexusMutual/frontend-react/blob/dev/public/logos/pendle.svg

## Onchain data

Product Name: steakLRT Symbiotic + Mellow + Pendle
Annex link (optional): https://drive.google.com/file/d/1GsnrABvsMtp29Ju0t-04vz5rfr2kvmWh/view?usp=sharing
Schedule link (optional): 

## SDK data

Category (i.e. Yield Optimizer. only for public products): Yield Optimizer 
Private or Public?: Public
Logo (attach link to Google Drive SVG file):
https://github.com/NexusMutual/frontend-react/blob/dev/public/logos/symbiotic.png
https://drive.google.com/file/d/1qllevh1q5H0N7Z3fYIMMBTvROieQsWmw/view?usp=sharing
https://github.com/NexusMutual/frontend-react/blob/dev/public/logos/pendle.svg

## Onchain data

Product Name: Re7LRT Symbiotic + Mellow + Pendle
Annex link (optional): https://drive.google.com/file/d/1yoKYlSCf34qLE9N96ypsFmTsuN3u1LfY/view?usp=sharing
Schedule link (optional): 

## SDK data

Category (i.e. Yield Optimizer. only for public products): Yield Optimizer
Private or Public?: Public
Logo (attach link to Google Drive SVG file):
https://github.com/NexusMutual/frontend-react/blob/dev/public/logos/symbiotic.png
https://drive.google.com/file/d/1qllevh1q5H0N7Z3fYIMMBTvROieQsWmw/view?usp=sharing
https://github.com/NexusMutual/frontend-react/blob/dev/public/logos/pendle.svg

**Comment by mixplore** [comment]
Adding the logos here:

![mellow-symbiotic](https://github.com/NexusMutual/sdk/assets/9848598/43ff0868-6f3e-4683-aa7e-1ffb7c29236c)
![symbiotic-mellow-pendle](https://github.com/NexusMutual/sdk/assets/9848598/831c0efe-b467-4be7-80a4-2944190416c3)

**Comment by rackstar** [comment]
@Gideonnn 

Dialectic (png):
![dialectic](https://github.com/NexusMutual/sdk/assets/15180121/3602d88b-df48-4bc2-89f9-1eb8eb43ddfd)
OUSD (svg):
![ousd](https://github.com/NexusMutual/sdk/assets/15180121/b10ad321-57a6-4d91-b3a1-36a2f1a69b69)
Spectra (jpg):
![spectra](https://github.com/NexusMutual/sdk/assets/15180121/f732a929-76fc-42af-90e7-49a213c9b958)
