### ISSUE TITLE
[listing] Update Wording for Fund Portfolio Cover

### ISSUE THREAD

**Issue by BraveNewDeFi** [NexusMutual/sdk#162]
# Product Type Listing Request

See this week's listing requests spreadsheet but updated wording is included below, as well: https://docs.google.com/spreadsheets/d/184TFMw3onXav_1YaFkdAcn295cJ1Qtk9sIQDO83rG_M/edit?usp=sharing

## Onchain data
**Product Type Name**: Fund Portfolio Cover
**Cover Wording PDF link**: https://drive.google.com/file/d/1UoXkfLIa3xxVxOjCUQLeq9XVR70s2qo9/view?usp=sharing

**Comment by rackstar** [comment]
closing issue as done:

https://github.com/NexusMutual/sdk/issues/161#issuecomment-2194558974
