### ISSUE TITLE
[listing] Product Listing Request | Week of 10 July

### ISSUE THREAD

**Issue by BraveNewDeFi** [NexusMutual/sdk#168]
# Product Listing Request

New Product Listing Spreadsheet: https://docs.google.com/spreadsheets/d/1rqF_1LKTaNAHTDlfuz5Coaabi58aTYrbu-yvL5lhq_A/edit?usp=sharing

## Onchain data

Product Name: Dialectic Chronograph
Annex link (optional): https://api.nexusmutual.io/ipfs/QmWsnT3utA3gqXSRdkaLcXNoQKYMASrDrbTv1aGvJ29pXK
Schedule link (optional):

## SDK data

Category (i.e. Yield Optimizer. only for public products): N/A 
Private or Public?: Private
Logo (attach link to Google Drive SVG file): https://drive.google.com/file/d/1oHyqsBj1asdXkbDnYGkkO-lRHlGy26Lr/view?usp=sharing

## Onchain data

Product Name: Dialectic Moonphase
Annex link (optional): https://api.nexusmutual.io/ipfs/Qmd6Mb1bPR4bTgrH5WX8ZHj6ViRssduBJHYiduogmgzUgx
Schedule link (optional): 

## SDK data

Category (i.e. Yield Optimizer. only for public products): N/A 
Private or Public?: Private
Logo (attach link to Google Drive SVG file): https://drive.google.com/file/d/1oHyqsBj1asdXkbDnYGkkO-lRHlGy26Lr/view?usp=sharing

## Onchain data

Product Name: Ether.fi Liquid ETH Vault
Annex link (optional): https://drive.google.com/file/d/1a5GqCA-xsGFlVncfAd13SEH6opjs7f5o/view?usp=sharing
Schedule link (optional):

## SDK data

Category (i.e. Yield Optimizer. only for public products): Yield Optimizer
Private or Public?: Public
Logo (attach link to Google Drive SVG file): https://github.com/NexusMutual/frontend-react/blob/dev/public/logos/etherfi.svg

## Onchain data

Product Name: Ether.fi Liquid Market-Neutral USD Vault
Annex link (optional): https://drive.google.com/file/d/10OrqHH17dPQKPm0Q-_Z-u3DKclM9q0kq/view?usp=sharing
Schedule link (optional): 

## SDK data

Category (i.e. Yield Optimizer. only for public products): Yield Optimizer 
Private or Public?: Public
Logo (attach link to Google Drive SVG file): https://github.com/NexusMutual/frontend-react/blob/dev/public/logos/etherfi.svg

## Onchain data

Product Name: DeltaPrime (UnoRe)
Annex link (optional): 
Schedule link (optional): https://drive.google.com/file/d/1d2anaw3h9KJ0dUglWeTcZNo3PpVARTXc/view?usp=sharing

## SDK data

Category (i.e. Yield Optimizer. only for public products): N/A
Private or Public?: Private
Logo (attach link to Google Drive SVG file): https://github.com/NexusMutual/frontend-react/blob/dev/public/logos/delta-prime.svg

## Onchain data

Product Name: Ether.fi Liquid King Karak LRT Vault
Annex link (optional): https://drive.google.com/file/d/1OHDus4dnIUiFts88Z32kd1LzDZj-Fplu/view?usp=sharing
Schedule link (optional): 

## SDK data

Category (i.e. Yield Optimizer. only for public products): Yield Optimizer 
Private or Public?: Public
Logo (attach link to Google Drive SVG file): https://github.com/NexusMutual/frontend-react/blob/dev/public/logos/etherfi.svg

## Onchain data

Product Name: Beefy CLM + Velodrome
Annex link (optional): https://drive.google.com/file/d/1lx1qL01Ol6T2QeJzUBSQ0N5wxLmjLiun/view?usp=sharing
Schedule link (optional): 

## SDK data

Category (i.e. Yield Optimizer. only for public products): Yield Optimizer  
Private or Public?: Public
Logo (attach link to Google Drive SVG file):
https://github.com/NexusMutual/frontend-react/blob/dev/public/logos/beefy.svg
https://github.com/NexusMutual/frontend-react/blob/dev/public/logos/velodrome2.svg

## Onchain data

Product Name: Beefy CLM + Aerodrome
Annex link (optional): https://drive.google.com/file/d/154khn0-ZctYXx0WYlX2xYeE6OPsCvIk3/view?usp=sharing
Schedule link (optional): 

## SDK data

Category (i.e. Yield Optimizer. only for public products): Yield Optimizer 
Private or Public?: Public
Logo (attach link to Google Drive SVG file):
https://github.com/NexusMutual/frontend-react/blob/dev/public/logos/beefy-aerodrome.svg

## Onchain data

Product Name: Beefy CLM + Camelot
Annex link (optional): https://drive.google.com/file/d/11BdAnZ3J383zmJe8m31oS-d_ZVZXc-N7/view?usp=sharing
Schedule link (optional):

## SDK data

Category (i.e. Yield Optimizer. only for public products): Yield Optimizer 
Private or Public?: Public
Logo (attach link to Google Drive SVG file):
https://github.com/NexusMutual/frontend-react/blob/dev/public/logos/beefy.svg
https://github.com/NexusMutual/frontend-react/blob/dev/public/logos/camelot.svg

## Onchain data

Product Name: Beefy CLM + Pancakeswap
Annex link (optional): https://drive.google.com/file/d/1_BFofrE_a5MKcNYFlu4ikwlyWh2cpr9p/view?usp=sharing
Schedule link (optional): 

## SDK data

Category (i.e. Yield Optimizer. only for public products): Yield Optimizer
Private or Public?: Public
Logo (attach link to Google Drive SVG file):
https://github.com/NexusMutual/frontend-react/blob/dev/public/logos/beefy.svg
https://github.com/NexusMutual/frontend-react/blob/dev/public/logos/pancakeswap.svg

## Onchain data

Product Name: Curve LlamaLend
Annex link (optional):
Schedule link (optional):

## SDK data

Category (i.e. Yield Optimizer. only for public products): Lending
Private or Public?: Public
Logo (attach link to Google Drive SVG file): https://github.com/NexusMutual/frontend-react/blob/dev/public/logos/curve.svg

## Onchain data

Product Name: Ramses Exchange
Annex link (optional):
Schedule link (optional): 

## SDK data

Category (i.e. Yield Optimizer. only for public products): DEX
Private or Public?: Public
Logo (attach link to Google Drive SVG file): https://drive.google.com/file/d/1jFQ_wUQL8CV5yUQmHsmR9USZrBplte4o/view?usp=sharing

**Comment by mixplore** [comment]
Bundle logos here 😎 

![Image](https://github.com/NexusMutual/sdk/assets/9848598/6cd17664-bb08-4d1d-b08f-7d76c978f650)
![Image](https://github.com/NexusMutual/sdk/assets/9848598/41f93898-52ef-494e-81cf-2ce44b3a7e1b)
![Image](https://github.com/NexusMutual/sdk/assets/9848598/263ce878-5a0b-4ea6-af9b-6f6806c481a0)
