### ISSUE TITLE
Products timestamp fix

### ISSUE THREAD

**Issue by mixplore** [NexusMutual/sdk#175]
### Context

After the latest `sdk` deployment, the products timestamp data appears to be `0` for all products. This now breaks some logic on the FE which relied on the timestamp value of the products to order them by the most recent ones from the past 14 days.  

**Question** is: Do we want to fix the timestamp value and keep the FE logic as is? Is the effort worth it? 
The other option would be to change the FE ordering logic (low effort) and use the `productId` to get the most recent `x` products where `x` = any number that makes sense business-wise.

**Comment by roxdanila** [comment]
We should revert to the old semantics where timestamp was fetched via "ProductSet" events
