### ISSUE TITLE
[listing] Product Listing Requests | Week of 28 August 2024

### ISSUE THREAD

**Issue by BraveNewDeFi** [NexusMutual/sdk#196]
# Product Listing Request

**New Product Listing Spreadsheet**: https://docs.google.com/spreadsheets/d/1VImzS9KXnVTkAmYZYXlpqSB8WURfxQZ6h7324zvCgn4/edit?usp=sharing

## PancakeSwap

**Product Name**: PancakeSwap
**Annex link (optional)**: 
**Schedule link (optional)**:
**Category** (i.e. Yield Optimizer. only for public products): DEX
**Private or Public?**: Public
**Logo** (attach link to Google Drive SVG file): https://github.com/NexusMutual/sdk/blob/master/src/logos/pancakeswap.svg

## Beefy + Velodrome

**Product Name**: Beefy + Velodrome
**Annex link (optional)**: https://drive.google.com/file/d/1wJ3rwyjcGSaXlLINR2tXHZJe85dryY08/view?usp=sharing
**Schedule link (optional)**:
**Category** (i.e. Yield Optimizer. only for public products): Yield Optimizer
**Private or Public?**: Public
**Logo** (attach link to Google Drive SVG file): 
* https://github.com/NexusMutual/sdk/blob/master/src/logos/014-beefy.svg
* https://github.com/NexusMutual/sdk/blob/master/src/logos/124-velodrome2.svg

## Base

**Product Name**: Base DeFi Pass
**Annex link (optional)**: https://drive.google.com/file/d/1puBEHnxlhSZn55ZPxifZjIoLymRMN1Xt/view?usp=sharing
**Schedule link (optional)**:
**Category** (i.e. Yield Optimizer. only for public products): N/A
**Private or Public?**: Private
**Logo** (attach link to Google Drive SVG file): https://drive.google.com/file/d/1Gbd4WkHXN-bqZA-u1e6-i4fp3dgpTg4T/view?usp=sharing

## Toros Finance Bitcoin Bull 3x

*We just need to update the Annex document for this existing listing.*

**Annex link (optional)**: https://drive.google.com/file/d/1C1dgbMNNGGHC3TL96fvJSkFXUdzi2X22/view
**Product ID**: 189

### Engineering Checklist

- [x] Craft transaction data payload
- [x] AB member to update onchain data
- [x] Update [SDK](https://github.com/NexusMutual/sdk)
- [x] Update [frontend-next](https://github.com/NexusMutual/frontend-next)
- [x] Update [frontend-react](https://github.com/NexusMutual/frontend-react)
- [x] Update [notification-processor](https://github.com/NexusMutual/notification-processor)
- [x] Update [event-scanner](https://github.com/NexusMutual/event-scanner) (if there are new private products)

**Comment by rackstar** [comment]
Closing as done
