### ISSUE TITLE
[listing] New Listing Requests | Week of 11 September 2024

### ISSUE THREAD

**Issue by BraveNewDeFi** [NexusMutual/sdk#208]
# Product Listing Request

**New Product Listing Spreadsheet**: https://docs.google.com/spreadsheets/d/1C4PgzNue2bZ8JEXXmWqPLRcnh6HOrAiQj7ZZkakTd80/edit?usp=sharing

## Euler Finance v2

**Product Name**: Euler Finance v2
**Annex link (optional)**: https://drive.google.com/file/d/13Wkx_pitA3a9Ae3ANvUbb-R3Pi820zpj/view?usp=sharing
**Schedule link (optional)**:
**Category** (i.e. Yield Optimizer. only for public products): Lending
**Private or Public?**: Public
**Logo** (attach link to Google Drive SVG file): https://github.com/NexusMutual/sdk/blob/master/src/logos/033-euler.svg

## Morpho + Morpho Vaults

**Product Name**: Morpho + Morpho Vaults
**Annex link (optional)**: https://drive.google.com/file/d/1p2wSpcYFUNqDl4y1ue-Jh9RlKP55rFoF/view?usp=sharing
**Schedule link (optional)**:
**Category** (i.e. Yield Optimizer. only for public products): Lending
**Private or Public?**: Public
**Logo** (attach link to Google Drive SVG file): https://github.com/NexusMutual/sdk/blob/master/src/logos/098-morpho.svg

## Ajna Finance

**Product Name**: Ajna Finance
**Annex link (optional)**: https://drive.google.com/file/d/1vYmEvXL4MOpLrkxK38trTwmnlpwl4yxn/view?usp=sharing
**Schedule link (optional)**:
**Category** (i.e. Yield Optimizer. only for public products): Lending
**Private or Public?**: Public
**Logo** (attach link to Google Drive SVG file): https://github.com/NexusMutual/sdk/blob/master/src/logos/105-ajna.svg

## Dolomite

**Product Name**: Dolomite
**Annex link (optional)**: 
**Schedule link (optional)**:
**Category** (i.e. Yield Optimizer. only for public products): Lending
**Private or Public?**: Public
**Logo** (attach link to Google Drive SVG file): https://drive.google.com/file/d/10nv1QUXyKAaaw3NrMP8caXCg-sX1h_fd/view?usp=sharing

## Steer Protocol

**Product Name**: Steer Protocol
**Annex link (optional)**: 
**Schedule link (optional)**:
**Category** (i.e. Yield Optimizer. only for public products): Lending
**Private or Public?**: Public
**Logo** (attach link to Google Drive SVG file): https://drive.google.com/file/d/1tQSNL72TJxyIcjfuM3zqk62x1Jjs7b4T/view?usp=sharing

## Relative Finance

**Product Name**: Relative Finance
**Annex link (optional)**: https://drive.google.com/file/d/1AR7pwNXhUhARDYd5UtYLMrH42bjGQrXj/view?usp=sharing
**Schedule link (optional)**:
**Category** (i.e. Yield Optimizer. only for public products): N/A
**Private or Public?**: Private
**Logo** (attach link to Google Drive SVG file): https://drive.google.com/file/d/1pXxWMX-0qkYSYzIKrP4mntQhiE8KA6Df/view?usp=sharing

## Base DeFi Pass

**Product Name**: Base DeFi Pass
**Annex link (optional)**: https://drive.google.com/file/d/1c8kyNpnHxlhXnrmZZ2Ftyj3Xp0pmvPEi/view?usp=sharing
**Schedule link (optional)**:
**Category** (i.e. Yield Optimizer. only for public products): N/A
**Private or Public?**: Private
**Logo** (attach link to Google Drive SVG file): https://github.com/NexusMutual/sdk/blob/master/src/logos/227-base.svg

## Contango + Morpho

**Product Name**: Contango + Morpho
**Annex link (optional)**: https://drive.google.com/file/d/1iQCe7JGDeD2HtdcnstCDp-oO1T8mvHrW/view?usp=sharing
**Schedule link (optional)**:
**Category** (i.e. Yield Optimizer. only for public products): Yield Optimizer
**Private or Public?**: Public
**Logo** (attach link to Google Drive SVG file): https://github.com/NexusMutual/sdk/blob/master/src/logos/224-contango-morpho.svg

We also need to deprecate the following listings
* Morpho Optimisers v1 | Product ID: 98
* Steakhouse MetaMorpho + Morpho Blue | Product ID: 172
* Re7 MetaMorpho + Morpho Blue | Product ID: 173
* Gauntlet MetaMorpho + Morpho Blue | Product ID: 175
* Block Analitica/B.Protocol MetaMorpho + Morpho Blue | Product ID: 180

### Engineering Checklist

- [x] Craft transaction data payload
- [x] AB member to update onchain data
- [x] #214
- [x] Update [frontend-next](https://github.com/NexusMutual/frontend-next)
- [x] Update [frontend-react](https://github.com/NexusMutual/frontend-react)
- [x] Update [notification-processor](https://github.com/NexusMutual/notification-processor)
- [x] Update [event-scanner](https://github.com/NexusMutual/event-scanner) (if there are new private products)
- [x] Update [cover-router](https://github.com/NexusMutual/cover-router) (if there are allowed pools priority ordering)

**Comment by rackstar** [comment]
## cover-router

Custom Pools Priority Ordering:

```
PRIORITY_POOLS_ORDER_227=8,23,22,2,1,5
PRIORITY_POOLS_ORDER_233=22,2,1,23
```

Also update the cover-router code to read these new env vars.

PR here: TODO

**Comment by rackstar** [comment]
done
