### ISSUE TITLE
[listing] Product Type Listing Request: Updated The Retail Mutual Wording

### ISSUE THREAD

**Issue by BraveNewDeFi** [NexusMutual/sdk#215]
# Product Type Listing Request

**New Product Type Listing Spreadsheet**: https://docs.google.com/spreadsheets/d/1N2ak6ghUDH7w2_8WG5iskqkiFbOZ0Qv0e2P8l7a1r2w/edit?usp=sharing

## Onchain data

*We only need to update the TRM wording onchain* 

**Product Type Name**: The Retail Mutual
**Cover Wording PDF link**: https://drive.google.com/file/d/17bx7zaBMwF1ncFntwnTysiDpRejebily/view?usp=sharing

### Engineering Checklist

- [ ] Craft transaction data payload
- [ ] AB member to update onchain data
- [ ] Update [SDK](https://github.com/NexusMutual/sdk)
- [ ] Update [frontend-next](https://github.com/NexusMutual/frontend-next)
- [ ] Update [frontend-react](https://github.com/NexusMutual/frontend-react)
- [ ] Update [notification-processor](https://github.com/NexusMutual/notification-processor)
- [ ] Update [event-scanner](https://github.com/NexusMutual/event-scanner) (if there are new private products)

**Comment by mixplore** [comment]
Done: https://nexusmutual.slack.com/archives/C076V9H4ND7/p1726758532371269?thread_ts=1726669998.478459&channel=C076V9H4ND7&message_ts=1726758532.371269
