### ISSUE TITLE
[listing] Product Listing Request | 2 October 2024

### ISSUE THREAD

**Issue by BraveNewDeFi** [NexusMutual/sdk#225]
# Product Listing Request

**New Product Listing Spreadsheet**: https://docs.google.com/spreadsheets/d/1HIXINHrJjW6PEn7OMsC_arShkGyVeyMu-L8smZ7iz1k/edit?usp=sharing

## Sky Protocol

*Rename Sky Money to Sky Protocol*

**Product Name**: Sky Protocol
**Annex link (optional)**:
**Schedule link (optional)**:
**Category** (i.e. Yield Optimizer. only for public products): Lending
**Private or Public?**: Public
**Logo** (attach link to Google Drive SVG file): https://github.com/NexusMutual/sdk/blob/master/src/logos/045-sky-money.svg

## Euler Finance v2

*Update Annex*

**Product Name**: Euler Finance v2
**Annex link (optional)**: https://drive.google.com/file/d/1QeS00HgWxIaMgyMqAPH88Z6ysHc-0QY7/view?usp=sharing
**Schedule link (optional)**:
**Category** (i.e. Yield Optimizer. only for public products): Lending
**Private or Public?**: Public
**Logo** (attach link to Google Drive SVG file): https://github.com/NexusMutual/sdk/blob/master/src/logos/228-euler-finance-v2.svg

## Morpho + Morpho Vaults

*Update Annex*

**Product Name**: Morpho + Morpho Vaults
**Annex link (optional)**: https://drive.google.com/file/d/1WLYeZtkIOz9dDjjSzBvLoLkFfnOreuzn/view?usp=sharing
**Schedule link (optional)**:
**Category** (i.e. Yield Optimizer. only for public products): Lending
**Private or Public?**: Public
**Logo** (attach link to Google Drive SVG file): https://github.com/NexusMutual/sdk/blob/master/src/logos/229-morpho-morpho-vaults.svg

### Engineering Checklist

- [x] Craft transaction data payload
- [x] AB member to update onchain data
- [x] Update [SDK](https://github.com/NexusMutual/sdk)
- [x] Update [frontend-next](https://github.com/NexusMutual/frontend-next)
- [x] Update [frontend-react](https://github.com/NexusMutual/frontend-react)
- [x] Update [notification-processor](https://github.com/NexusMutual/notification-processor)
- [ ] Update [event-scanner](https://github.com/NexusMutual/event-scanner) (if there are new private products)
- [ ] Update [cover-router](https://github.com/NexusMutual/cover-router) .env (if there are allowed pools priority ordering)

**Comment by rackstar** [comment]
closing as done
