### ISSUE TITLE
[listing] Listing Request | 9 October 2024

### ISSUE THREAD

**Issue by BraveNewDeFi** [NexusMutual/sdk#228]
# Product Listing Request

**New Product Listing Spreadsheet**: https://docs.google.com/spreadsheets/d/11DSi2SmxktOQXxulMGoEU9Csd0X_uau1ocbyu7_Zquo/edit?usp=sharing

## Morpho + Morpho Vaults

*Just updating the Annex*

**Product Name**: Morpho + Morpho Vaults
**Annex link (optional)**: https://drive.google.com/file/d/1jYfrbo4S1ShNUBQ6JtkKRLHlfVFndE1a/view?usp=sharing
**Schedule link (optional)**:
**Category** (i.e. Yield Optimizer. only for public products): Lending
**Private or Public?**: Public
**Logo** (attach link to Google Drive SVG file): https://github.com/NexusMutual/sdk/blob/dev/src/logos/229-morpho-morpho-vaults.svg

## Euler Finance v2

*Just updating the Annex*

**Product Name**: Euler Finance v2
**Annex link (optional)**: https://drive.google.com/file/d/1txav9DH3-KevxDv20_LeLxZ5_lgcpJY3/view?usp=sharing
**Schedule link (optional)**:
**Category** (i.e. Yield Optimizer. only for public products): Lending
**Private or Public?**: Public
**Logo** (attach link to Google Drive SVG file): https://github.com/NexusMutual/sdk/blob/dev/src/logos/228-euler-finance-v2.svg

## Request Finance

*Just updating the Annex*

**Product Name**: Request Finance
**Annex link (optional)**: https://drive.google.com/file/d/18IYweUcDcK3vMdWBK5mncjs-mmOZjwQD/view?usp=sharing
**Schedule link (optional)**:
**Category** (i.e. Yield Optimizer. only for public products): N/A
**Private or Public?**: Private
**Logo** (attach link to Google Drive SVG file): https://github.com/NexusMutual/sdk/blob/dev/src/logos/164-request-finance.svg

## Base DeFi Pass

*Just updating the Annex*

**Product Name**: Base DeFi Pass
**Annex link (optional)**: https://drive.google.com/file/d/1jq9u0uAzSGcw2AjxQfzQm7VArRdYXxca/view?usp=sharing
**Schedule link (optional)**:
**Category** (i.e. Yield Optimizer. only for public products): N/A
**Private or Public?**: Private
**Logo** (attach link to Google Drive SVG file): https://github.com/NexusMutual/sdk/blob/dev/src/logos/227-base.svg

### Engineering Checklist

- [x] Craft transaction data payload
- [x] AB member to update onchain data
- [x] Update [SDK](https://github.com/NexusMutual/sdk)
- [x] Update [frontend-next](https://github.com/NexusMutual/frontend-next)
- [x] Update [frontend-react](https://github.com/NexusMutual/frontend-react)
- [x] Update [notification-processor](https://github.com/NexusMutual/notification-processor)
- [ ] Update [event-scanner](https://github.com/NexusMutual/event-scanner) (if there are new private products)
- [ ] Update [cover-router](https://github.com/NexusMutual/cover-router) .env (if there are allowed pools priority ordering)

**Comment by rackstar** [comment]
marking as done
