### ISSUE TITLE
Listing Requests | Week of 11 November 2024

### ISSUE THREAD

**Issue by BraveNewDeFi** [NexusMutual/sdk#235]
# Product Listing Request

**New Product Listing Spreadsheet**: https://docs.google.com/spreadsheets/d/1CsHYqK9CV2cTGtuNM4_fMk0Rxr6YXxQOmyCdNYcL0Q8/edit?usp=sharing

## Everstake

**Product Name**: Everstake
**Annex link (optional)**: https://drive.google.com/file/d/1b3RGcjYTOetb8FbHph30I9uB8keSNfue/view?usp=sharing
**Schedule link (optional)**:
**Category** (i.e. Yield Optimizer. only for public products): N/A
**Private or Public?**: Private
**Logo** (attach link to Google Drive SVG file): https://drive.google.com/file/d/1pBbUpYMZHXmi57aMFk8pnmo3Vz0wBUJV/view?usp=sharing

## Ensuro

**Product Name**: Ensuro
**Annex link (optional)**: https://drive.google.com/file/d/12KjCEOIfY1VoSl2I7fA-SIr58bcVDq_p/view?usp=sharing
**Schedule link (optional)**:
**Category** (i.e. Yield Optimizer. only for public products): N/A
**Private or Public?**: Private
**Logo** (attach link to Google Drive SVG file): https://drive.google.com/file/d/1aDvsZB1tQo7JNgm9iPdH9ltrT7GqFd5L/view?usp=sharing

## Savings crvUSD (scrvUSD)

**Product Name**: Savings crvUSD (scrvUSD)
**Annex link (optional)**:
**Schedule link (optional)**:
**Category** (i.e. Yield Optimizer. only for public products): Yield Optimizer
**Private or Public?**: Public
**Logo** (attach link to Google Drive SVG file): https://drive.google.com/file/d/1ecHrgHpw_cFLPqZXq-TbFBMf5iQOA8j7/view?usp=sharing

## Lombard DeFi Vault

**Product Name**: Lombard DeFi Vault
**Annex link (optional)**: https://drive.google.com/file/d/1HGaxtgM3FpqYDLOEvHFAJkfO1zRdYvYL/view?usp=sharing
**Schedule link (optional)**:
**Category** (i.e. Yield Optimizer. only for public products): Yield Optimizer
**Private or Public?**: Public
**Logo** (attach link to Google Drive SVG file): https://drive.google.com/file/d/1TiNMaNJDYeajANzwczNegcW3gepsoEeH/view?usp=sharing

## Liquity v2

**Product Name**: Liquity v2
**Annex link (optional)**:
**Schedule link (optional)**:
**Category** (i.e. Yield Optimizer. only for public products): Lending
**Private or Public?**: Public
**Logo** (attach link to Google Drive SVG file): https://drive.google.com/file/d/1UYbUJM-JeQxxGBr0F7Cl3_hfINv9Jru3/view?usp=sharing

## CoW AMM

**Product Name**: CoW AMM
**Annex link (optional)**:
**Schedule link (optional)**:
**Category** (i.e. Yield Optimizer. only for public products): DEX
**Private or Public?**: Public
**Logo** (attach link to Google Drive SVG file): https://drive.google.com/file/d/1QwwiHCJUgK5Dsm82m2BuKEPCBn5fAnhv/view?usp=sharing

## Ether.fi Liquid ETH Vault

*Only Updating the Annex*

**Product Name**: Ether.fi Liquid ETH Vault
**Annex link (optional)**: https://drive.google.com/file/d/1xPjhRbfHmcfaLNGlQ-6r-D7Sr9ahWK7X/view?usp=sharing
**Schedule link (optional)**:
**Category** (i.e. Yield Optimizer. only for public products): Yield Optimizer
**Private or Public?**: Public
**Logo** (attach link to Google Drive SVG file): https://github.com/NexusMutual/sdk/blob/dev/src/logos/150-etherfi.svg

## Ether.fi Liquid Market-Neutral USD Vault

*Only Updating the Annex*

**Product Name**: Ether.fi Liquid Market-Neutral USD Vault
**Annex link (optional)**: https://drive.google.com/file/d/1Jxqo7qT-WeVleOaia8r-YGfwIXNUgrLU/view?usp=sharing
**Schedule link (optional)**:
**Category** (i.e. Yield Optimizer. only for public products): Yield Optimizer
**Private or Public?**: Public
**Logo** (attach link to Google Drive SVG file): https://github.com/NexusMutual/sdk/blob/dev/src/logos/165-etherfi.svg

## Ether.fi Liquid King Karak LRT Vault

*Only Updating the Annex*

**Product Name**: Ether.fi Liquid King Karak LRT Vault
**Annex link (optional)**: https://drive.google.com/file/d/1VMNaBmQeeTpdwRx7ce3GrAv-pLLCc-4X/view?usp=sharing
**Schedule link (optional)**:
**Category** (i.e. Yield Optimizer. only for public products): Yield Optimizer
**Private or Public?**: Public
**Logo** (attach link to Google Drive SVG file): https://github.com/NexusMutual/sdk/blob/dev/src/logos/209-etherfi-liquid-king-karak-lrt-vault.svg

## Ether.fi Liquid eBTC Bitcoin LRT Vault

*Only Updating the Annex*

**Product Name**: Ether.fi Liquid eBTC Bitcoin LRT Vault
**Annex link (optional)**: https://drive.google.com/file/d/1irwb6gx649rutdAB7lNMBvSTQi_-UgY1/view?usp=sharing
**Schedule link (optional)**:
**Category** (i.e. Yield Optimizer. only for public products): Yield Optimizer
**Private or Public?**: Public
**Logo** (attach link to Google Drive SVG file): https://github.com/NexusMutual/sdk/blob/dev/src/logos/221-etherfi-liquid-ebtc-bitcoin-lrt-vault.svg

## Euler Finance v2

*Only Updating the Annex*

**Product Name**: Euler Finance v2
**Annex link (optional)**: https://drive.google.com/file/d/1RR7qyjghSg-OXy5oxORidxfueIClySOo/view?usp=sharing
**Schedule link (optional)**:
**Category** (i.e. Yield Optimizer. only for public products): Lending
**Private or Public?**: Public
**Logo** (attach link to Google Drive SVG file): https://github.com/NexusMutual/sdk/blob/dev/src/logos/228-euler-finance-v2.svg

## Morpho + Morpho Vaults

*Only Updating the Annex*

**Product Name**: Morpho + Morpho Vaults
**Annex link (optional)**: https://drive.google.com/file/d/1C4fyDfIhCEdec2SVrK8kGDMJOy30AJ06/view?usp=sharing
**Schedule link (optional)**:
**Category** (i.e. Yield Optimizer. only for public products): Lending
**Private or Public?**: Public
**Logo** (attach link to Google Drive SVG file): https://github.com/NexusMutual/sdk/blob/dev/src/logos/229-morpho-morpho-vaults.svg

**Comment by rackstar** [comment]
- [x] Craft transaction data payload
- [x] AB member to update onchain data
- [x] Update [SDK](https://github.com/NexusMutual/sdk)
- [x] Update [frontend-next](https://github.com/NexusMutual/frontend-next)
- [x] Update [frontend-react](https://github.com/NexusMutual/frontend-react)
- [ ] Update [notification-processor](https://github.com/NexusMutual/notification-processor)
- [ ] Update [event-scanner](https://github.com/NexusMutual/event-scanner) (if there are new private products)
- [ ] Update [cover-router](https://github.com/NexusMutual/cover-router) .env (if there are allowed pools priority ordering)
